### ISSUE TITLE
Proxy triggers Mozilla observatory warning related to Subresource Integrity  (script loaded using // instead of https)

### ISSUE THREAD

**Issue by oldrup** [plausible/wordpress#157]
Hey. During my WP 6.3 related security checkup, I noticed that my Mozilla Observatory score suffered a big hit from rating B to F

Before:
![image](https://github.com/plausible/wordpress/assets/17141205/fad2595e-9202-42d9-8a2b-c80f6442c06c)

After:
![image](https://github.com/plausible/wordpress/assets/17141205/6cc713b8-09b8-4531-9d1b-a1af61fecbb4)

According to Mozilla, the culprit is, and I quote: _"Subresource Integrity (SRI) not implemented, and external scripts are loaded over HTTP or use protocol-relative URLs via src="//...""_

![image](https://github.com/plausible/wordpress/assets/17141205/3caebd34-fe2b-43fc-983c-caa8030cde1c)

Observatory only triggers the warning, when Plausible and its proxy is enabled. That's likely because it addresses the "secret script" using relative URLs:

Proxy code in HTML:
![image](https://github.com/plausible/wordpress/assets/17141205/bbfed22b-deda-498b-bc61-e132671f4fef)

I don't know if it's possible to just use HTTPS, assuming web admins using Plausible proxy, do have their certificates in place, or?

I think this should be reproducible - it is on my sites. Not critical, will just disable Proxy for now - but I really like the feature.

**Comment by Dan0sz** [comment]
Oof! Yes, we used protocol relative URLs, to avoid a WordPress related quirk that sometimes (e.g. when using a reverse proxy in Nginx) the `is_ssl()` check fails and it'll enqueue the script using non-SSL URLs.

But, in all honesty, I wasn't aware of this check.

I'll add some extra checks, so https:// is used if is_ssl() succeeds. Something like that.

**Comment by oldrup** [comment]
Just curious - is there anything I can to do help here? Testing any ideas?

**Comment by Dan0sz** [comment]
Hi!

This is fixed in the next release. The next release will no longer use protocol relative URLs.

**Comment by oldrup** [comment]
Hey! First, congratulations on the new release - very elegant 🎉

But, I must admit, I'm still experiencing poor ratings from Mozilla Observatory with proxy enabled, and the script appears, on my installation, to be loaded via a relative URL still. Screenshot from oldrup.dk with Plausible plugin 2.0.1 installed and **proxy enabled**
![image](https://github.com/plausible/wordpress/assets/17141205/d4d442f0-c3a4-4dd1-b4df-790b1bb5f55b)

Mozilla observatory grade for oldrup.dk:
https://observatory.mozilla.org/analyze/oldrup.dk

On another site of mine, oldrup.net, the proxy is **disabled**, and the score is better:
https://observatory.mozilla.org/analyze/oldrup.net

- I did all the disabling cache, reloading, re-testing a couple of times.
- SSL is, of course, enabled, and WordPress site health, is, well, 100% healthy. 

Any ideas?

**Comment by Dan0sz** [comment]
Just to be sure, can you disable and enable the Proxy? Perhaps the old, relative URLs are still stored in the DB.

**Comment by oldrup** [comment]
Uh. @Dan0sz that appears to be the trick. As I actually reinstalled the Plausible 2.0.3 plugin entirely, and completed the entire onbording experience - which is very well done btw - I assumed all settings were cleared.

But toggling the proxy option off and on again, did the trick!

Screenshot: script now loaded from absolute https:// url:
![image](https://github.com/plausible/wordpress/assets/17141205/c225b572-62f4-4e44-9336-388c9dcb6623)

And Mozilla is much happier (getting above B+ with WordPress is hard)
![image](https://github.com/plausible/wordpress/assets/17141205/72b5f58a-8054-43a2-8edb-a42c8d1702ac)

And Hardenize is happy too:
![image](https://github.com/plausible/wordpress/assets/17141205/050e7f5f-8fe5-458e-8969-dbd8a1f8ed0b)

It's nice to be able to demonstrate that we can offer adequate statistics while honoring people's privacy, have great performance and good security.

Thanks for the help!
